# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/contextpack',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/contextpack',
                'lib_path': 'contextpack'},
  'syms': {'contextpack.core': {'contextpack.core.foo': ('core.html#foo', 'contextpack/core.py')}}}
